### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alphapapa** [dfeich/org-listcruncher#4]
Hi,

This is looking really cool! One suggestion: what if the attribute list used lisp syntax, e.g. `:key1 val1 :key2 val2`? That way commas wouldn't matter, and it would appeal to elispers.  :)

**Comment by dfeich** [comment]
Hi
Yes. But I was trying here to appeal more to the normal user. I am already acquiring a reputation in my work place of being a bit exotic with the lisp and emacs evangelism (but several guys of my section have successfully converted to Emacs + Org in the last 3 years).  :-)

I made the list item parsing and also the consolidation function customizable. I would like to later provide a few such functions out of the box. But need to work on it.
At the moment the customization must happen with configuring the elisp variables or through the customization interface, but I guess I should also allow to pass the function to use as an additional optional argument, because a user may want to use more than a single parsing function.

The current default parsing function needs to be made a bit more powerful. But I have first to get a bit more experience and feedback from people using it in my group or others.

**Comment by alphapapa** [comment]
Converting several people to Emacs and Org is impressive! Sounds like you're doing great. :)  Thanks.
