### ISSUE TITLE
Adding a formula to generated table

### ISSUE THREAD

**Issue by leosala** [dfeich/org-listcruncher#5]
As I am using this cool tool (thanks!) for generating budget tables, one interesting feature would be to have a formulas inside specific fields (e.g. to generate the total budget). Example:

```
+  Shopping list
    - item: banana (color: yellow, cost: 0.50)
    - item: apple (color: red, cost: 0.25)
    - item: total (cost: vsum())
```

with result:

```
|              | color    | cost |
| ---------- | --------- | ----- |  
| banana | yellow | 0.50 |
| apple    | red      | 0.25 |
| ---------- | --------- | ----- | 
| total      |            | 0.75 | 
```

The way the formula is written in the items list is just a suggestion :)

I would not restrict the method to `vsum` if possible, as for example I could think that using e.g. `vmean` would be useful in some cases

**Comment by dfeich** [comment]
Sorry, the issue was prematurely closed automatically by the commit I did, since I referenced the issue as resolved in the commit message.

I think this is best accomplished outside of listcruncher with a bit of additional lisp. I just added a commit with an example to the README (look for the heading `Adding a table formula to the resulting table`). Here the basic example

```elisp
     (princ (orgtbl-to-orgtbl
     	(append (org-listcruncher-to-table listname) '(hline ("Total")))
     	'(:tend "#+TBLFM: @>$3=vsum(@I..@II)")))
```
A deeper integration into listcruncher itself I would currently not do, since the definition of a generic enough API for it seems difficult, since there are so many things you may want to do in an org table function row. The functions have to define cell ranges, you may not only want to add a row at the end, but maybe also a column, etc. So, since the above can be accomplished easily with minimal additional code, I recommend using that solution. I think an implementation in listcruncher would allways be too narrow.
